'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ImageFile
    Public Property Id As System.Guid
    Public Property Name As String
    Public Property FileSize As Nullable(Of Integer)
    Public Property FilePath As String
    Public Property Uploaded_User_Id As System.Guid

End Class
