'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Namespace BulletinBoard_OJT.DB_Entity
    Partial Public Class Posts
        Public Property Id As System.Guid
        <Required>
        Public Property Title As String
        <Required>
        Public Property Description As String
        <Required>
        Public Property Status As String = "1"
        <Required>
        Public Property Created_At As Date
        <Required>
        Public Property Updated_User_Id As System.Guid
        <Required>
        Public Property Created_User_Id As System.Guid
        <Required>
        Public Property Updated_At As Date

        Public Overridable Property User1 As Users
        Public Overridable Property User As Users

    End Class
End Namespace
