'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Namespace BulletinBoard_OJT.DB_Entity
    Partial Public Class Roles
        Public Property Id As System.Guid
        Public Property Type As String

        Public Overridable Property Users As ICollection(Of Users) = New HashSet(Of Users)

    End Class
End Namespace