'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations
Imports System.ComponentModel.DataAnnotations.Schema

Namespace BulletinBoard_OJT.DB_Entity
    Partial Public Class Users
        Public Property Id As System.Guid
        <Required>
        Public Property Name As String
        <Required>
        <EmailAddress>
        Public Property Email As String
        <Required>
        <StringLength(100, ErrorMessage:="The {0} must be at least {2} characters long.", MinimumLength:=6)>
        <DataType(DataType.Password)>
        Public Property Password As String

        <Compare("Password", ErrorMessage:="Password and confirmation password do not match.")>
        Public Property ConfirmPassowrd As String

        Public Property Profile As String
        Public Property ImageFile As HttpPostedFileBase
        <Required>
        Public Property Phone As String
        <Required>
        Public Property Address As String
        Public Property Dob As Nullable(Of Date)
        Public Property Deleted_User_Id As Nullable(Of System.Guid)
        <Required>
        Public Property Created_At As Date
        <Required>
        Public Property Updated_At As Date
        Public Property Deleted_At As Nullable(Of Date)
        <Required>
        Public Property Is_Deleted As String = "active"
        <Required>
        Public Property Roles_Id As System.Guid
        <Required>
        Public Property Created_User_Id As System.Guid
        <Required>
        Public Property Updated_User_Id As System.Guid

        Public Overridable Property Role As Roles
        Public Overridable Property Users1 As ICollection(Of Users) = New HashSet(Of Users)
        Public Overridable Property User As Users
        Public Overridable Property Users2 As ICollection(Of Users) = New HashSet(Of Users)
        Public Overridable Property User1 As Users
        Public Overridable Property Posts1 As ICollection(Of Posts) = New HashSet(Of Posts)
        Public Overridable Property Posts As ICollection(Of Posts) = New HashSet(Of Posts)

    End Class
End Namespace
